export const tc = `###### **Website Terms and Conditions [Text Format]**
Last updated [month day, year]

##### **AGREEMENT TO TERMS**

These Terms and Conditions constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”) and [business entity name] (“we,” “us” or “our”), concerning your access to and use of the [website name.com] website as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto (collectively, the “Site”).

You agree that by accessing the Site, you have read, understood, and agree to be bound by all of these Terms and Conditions. If you do not agree with all of these Terms and Conditions, then you are expressly prohibited from using the Site and you must discontinue use immediately.

Supplemental terms and conditions or documents that may be posted on the Site from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Terms and Conditions at any time and for any reason.

We will alert you about any changes by updating the “Last updated” date of these Terms and Conditions, and you waive any right to receive specific notice of each such change.

It is your responsibility to periodically review these Terms and Conditions to stay informed of updates. You will be subject to, and will be deemed to have been made aware of and to have accepted, the changes in any revised Terms and Conditions by your continued use of the Site after the date such revised Terms and Conditions are posted.

The information provided on the Site is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject us to any registration requirement within such jurisdiction or country.

Accordingly, those persons who choose to access the Site from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.

These terms and conditions were generated by Termly’s Terms and Conditions Generator.

Option 1: The Site is intended for users who are at least 18 years old. Persons under the age of 18 are not permitted to register for the Site.

Option 2: [The Site is intended for users who are at least 13 years of age.] All users who are minors in the jurisdiction in which they reside (generally under the age of 18) must have the permission of, and be directly supervised by, their parent or guardian to use the Site. If you are a minor, you must have your parent or guardian read and agree to these Terms and Conditions prior to you using the Site.

##### **INTELLECTUAL PROPERTY RIGHTS**

Unless otherwise indicated, the Site is our proprietary property and all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site (collectively, the “Content”) and the trademarks, service marks, and logos contained therein (the “Marks”) are owned or controlled by us or licensed to us, and are protected by copyright and trademark laws and various other intellectual property rights and unfair competition laws of the United States, foreign jurisdictions, and international conventions.

The Content and the Marks are provided on the Site “AS IS” for your information and personal use only. Except as expressly provided in these Terms and Conditions, no part of the Site and no Content or Marks may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.

Provided that you are eligible to use the Site, you are granted a limited license to access and use the Site and to download or print a copy of any portion of the Content to which you have properly gained access solely for your personal, non-commercial use. We reserve all rights not expressly granted to you in and to the Site, the Content and the Marks.

##### **USER REPRESENTATIONS**

By using the Site, you represent and warrant that:

1. all registration information you submit will be true, accurate, current, and complete;
2. you will maintain the accuracy of such information and promptly update such registration information as necessary;
3. you have the legal capacity and you agree to comply with these Terms and Conditions;
4. you are not under the age of 13;
5. not a minor in the jurisdiction in which you reside [, or if a minor, you have received parental permission to use the Site];
6. you will not access the Site through automated or non-human means, whether through a bot, script, or otherwise;
7. you will not use the Site for any illegal or unauthorized purpose;
8. your use of the Site will not violate any applicable law or regulation.

If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Site (or any portion thereof).

##### **USER REGISTRATION**

You may be required to register with the Site. You agree to keep your password confidential and will be responsible for all use of your account and password. We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable.

##### **PROHIBITED ACTIVITIES**

You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.

As a user of the Site, you agree not to:

1. systematically retrieve data or other content from the Site to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.
2. make any unauthorized use of the Site, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating user accounts by automated means or under false pretenses.
3. use a buying agent or purchasing agent to make purchases on the Site.
4. use the Site to advertise or offer to sell goods and services.
5. circumvent, disable, or otherwise interfere with security-related features of the Site, including features that prevent or restrict the use or copying of any Content or enforce limitations on the use of the Site and/or the Content contained therein.
6. engage in unauthorized framing of or linking to the Site.
7. trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords;
8. make improper use of our support services or submit false reports of abuse or misconduct.
9. engage in any automated use of the system, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools.
10. interfere with, disrupt, or create an undue burden on the Site or the networks or services connected to the Site.
11. attempt to impersonate another user or person or use the username of another user.
12. sell or otherwise transfer your profile.
13. use any information obtained from the Site in order to harass, abuse, or harm another person.
14. use the Site as part of any effort to compete with us or otherwise use the Site and/or the Content for any revenue-generating endeavor or commercial enterprise.
15. decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Site.
16. attempt to bypass any measures of the Site designed to prevent or restrict access to the Site, or any portion of the Site.
17. harass, annoy, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Site to you.
18. delete the copyright or other proprietary rights notice from any Content.
19. copy or adapt the Site’s software, including but not limited to Flash, PHP, HTML, JavaScript, or other code.
20. upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material, including excessive use of capital letters and spamming (continuous posting of repetitive text), that interferes with any party’s uninterrupted use and enjoyment of the Site or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Site.
21. upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats (“gifs”), 1×1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as “spyware” or “passive collection mechanisms” or “pcms”).
22. except as may be the result of standard search engine or Internet browser usage, use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Site, or using or launching any unauthorized script or other software.
23. disparage, tarnish, or otherwise harm, in our opinion, us and/or the Site.
24. use the Site in a manner inconsistent with any applicable laws or regulations.
25. [other]

##### **USER GENERATED CONTRIBUTIONS**

The Site may invite you to chat, contribute to, or participate in blogs, message boards, online forums, and other functionality, and may provide you with the opportunity to create, submit, post, display, transmit, perform, publish, distribute, or broadcast content and materials to us or on the Site, including but not limited to text, writings, video, audio, photographs, graphics, comments, suggestions, or personal information or other material (collectively, “Contributions”).

Contributions may be viewable by other users of the Site and through third-party websites. As such, any Contributions you transmit may be treated as non-confidential and non-proprietary. When you create or make available any Contributions, you thereby represent and warrant that:

the creation, distribution, transmission, public display, or performance, and the accessing, downloading, or copying of your Contributions do not and will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark, trade secret, or moral rights of any third party.
you are the creator and owner of or have the necessary licenses, rights, consents, releases, and permissions to use and to authorize us, the Site, and other users of the Site to use your Contributions in any manner contemplated by the Site and these Terms and Conditions.
you have the written consent, release, and/or permission of each and every identifiable individual person in your Contributions to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of your Contributions in any manner contemplated by the Site and these Terms and Conditions.
your Contributions are not false, inaccurate, or misleading.
your Contributions are not unsolicited or unauthorized advertising, promotional materials, pyramid schemes, chain letters, spam, mass mailings, or other forms of solicitation.
your Contributions are not obscene, lewd, lascivious, filthy, violent, harassing, libelous, slanderous, or otherwise objectionable (as determined by us).
your Contributions do not ridicule, mock, disparage, intimidate, or abuse anyone.
your Contributions do not advocate the violent overthrow of any government or incite, encourage, or threaten physical harm against another.
your Contributions do not violate any applicable law, regulation, or rule.
your Contributions do not violate the privacy or publicity rights of any third party.
your Contributions do not contain any material that solicits personal information from anyone under the age of 18 or exploits people under the age of 18 in a sexual or violent manner.
your Contributions do not violate any federal or state law concerning child pornography, or otherwise intended to protect the health or well-being of minors;
your Contributions do not include any offensive comments that are connected to race, national origin, gender, sexual preference, or physical handicap.
your Contributions do not otherwise violate, or link to material that violates, any provision of these Terms and Conditions, or any applicable law or regulation.
Any use of the Site in violation of the foregoing violates these Terms and Conditions and may result in, among other things, termination or suspension of your rights to use the Site.

##### **CONTRIBUTION LICENSE**

By posting your Contributions to any part of the Site [or making Contributions accessible to the Site by linking your account from the Site to any of your social networking accounts], you automatically grant, and you represent and warrant that you have the right to grant, to us an unrestricted, unlimited, irrevocable, perpetual, non-exclusive, transferable, royalty-free, fully-paid, worldwide right, and license to host, use, copy, reproduce, disclose, sell, resell, publish, broadcast, retitle, archive, store, cache, publicly perform, publicly display, reformat, translate, transmit, excerpt (in whole or in part), and distribute such Contributions (including, without limitation, your image and voice) for any purpose, commercial, advertising, or otherwise, and to prepare derivative works of, or incorporate into other works, such Contributions, and grant and authorize sublicenses of the foregoing. The use and distribution may occur in any media formats and through any media channels.

This license will apply to any form, media, or technology now known or hereafter developed, and includes our use of your name, company name, and franchise name, as applicable, and any of the trademarks, service marks, trade names, logos, and personal and commercial images you provide. You waive all moral rights in your Contributions, and you warrant that moral rights have not otherwise been asserted in your Contributions.

We do not assert any ownership over your Contributions. You retain full ownership of all of your Contributions and any intellectual property rights or other proprietary rights associated with your Contributions. We are not liable for any statements or representations in your Contributions provided by you in any area on the Site.

You are solely responsible for your Contributions to the Site and you expressly agree to exonerate us from any and all responsibility and to refrain from any legal action against us regarding your Contributions.

We have the right, in our sole and absolute discretion, (1) to edit, redact, or otherwise change any Contributions; (2) to re-categorize any Contributions to place them in more appropriate locations on the Site; and (3) to pre-screen or delete any Contributions at any time and for any reason, without notice. We have no obligation to monitor your Contributions.

GUIDELINES FOR REVIEWS

We may provide you areas on the Site to leave reviews or ratings. When posting a review, you must comply with the following criteria:

(1) you should have firsthand experience with the person/entity being reviewed;

(2) your reviews should not contain offensive profanity, or abusive, racist, offensive, or hate language;

(3) your reviews should not contain discriminatory references based on religion, race, gender, national origin, age, marital status, sexual orientation, or disability;

(4) your reviews should not contain references to illegal activity;

(5) you should not be affiliated with competitors if posting negative reviews;

(6) you should not make any conclusions as to the legality of conduct;

(7) you may not post any false or misleading statements;

(8) you may not organize a campaign encouraging others to post reviews, whether positive or negative.

We may accept, reject, or remove reviews in our sole discretion. We have absolutely no obligation to screen reviews or to delete reviews, even if anyone considers reviews objectionable or inaccurate. Reviews are not endorsed by us, and do not necessarily represent our opinions or the views of any of our affiliates or partners.

We do not assume liability for any review or for any claims, liabilities, or losses resulting from any review. By posting a review, you hereby grant to us a perpetual, non-exclusive, worldwide, royalty-free, fully-paid, assignable, and sublicensable right and license to reproduce, modify, translate, transmit by any means, display, perform, and/or distribute all content relating to reviews.

MOBILE APPLICATION LICENSE

Use License

If you access the Site via a mobile application, then we grant you a revocable, non-exclusive, non-transferable, limited right to install and use the mobile application on wireless electronic devices owned or controlled by you, and to access and use the mobile application on such devices strictly in accordance with the terms and conditions of this mobile application license contained in these Terms and Conditions.

You shall not:

(1) decompile, reverse engineer, disassemble, attempt to derive the source code of, or decrypt the application;

(2) make any modification, adaptation, improvement, enhancement, translation, or derivative work from the application;

(3) violate any applicable laws, rules, or regulations in connection with your access or use of the application;

(4) remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) posted by us or the licensors of the application;

(5) use the application for any revenue generating endeavor, commercial enterprise, or other purpose for which it is not designed or intended;

(6) make the application available over a network or other environment permitting access or use by multiple devices or users at the same time;

(7) use the application for creating a product, service, or software that is, directly or indirectly, competitive with or in any way a substitute for the application;

(8) use the application to send automated queries to any website or to send any unsolicited commercial e-mail;

(9) use any proprietary information or any of our interfaces or our other intellectual property in the design, development, manufacture, licensing, or distribution of any applications, accessories, or devices for use with the application.

Apple and Android Devices

The following terms apply when you use a mobile application obtained from either the Apple Store or Google Play (each an “App Distributor”) to access the Site:

(1) the license granted to you for our mobile application is limited to a non-transferable license to use the application on a device that utilizes the Apple iOS or Android operating systems, as applicable, and in accordance with the usage rules set forth in the applicable App Distributor’s terms and conditions;

(2) we are responsible for providing any maintenance and support services with respect to the mobile application as specified in the terms and conditions of this mobile application license contained in these Terms and Conditions or as otherwise required under applicable law, and you acknowledge that each App Distributor has no obligation whatsoever to furnish any maintenance and support services with respect to the mobile application;

(3) in the event of any failure of the mobile application to conform to any applicable warranty, you may notify the applicable App Distributor, and the App Distributor, in accordance with its terms and policies, may refund the purchase price, if any, paid for the mobile application, and to the maximum extent permitted by applicable law, the App Distributor will have no other warranty obligation whatsoever with respect to the mobile application;

(4) you represent and warrant that (i) you are not located in a country that is subject to a U.S. government embargo, or that has been designated by the U.S. government as a “terrorist supporting” country and (ii) you are not listed on any U.S. government list of prohibited or restricted parties;

(5) you must comply with applicable third-party terms of agreement when using the mobile application, e.g., if you have a VoIP application, then you must not be in violation of their wireless data service agreement when using the mobile application;

6) you acknowledge and agree that the App Distributors are third-party beneficiaries of the terms and conditions in this mobile application license contained in these Terms and Conditions, and that each App Distributor will have the right (and will be deemed to have accepted the right) to enforce the terms and conditions in this mobile application license contained in these Terms and Conditions against you as a third-party beneficiary thereof.

SOCIAL MEDIA

As part of the functionality of the Site, you may link your account with online accounts you have with third-party service providers (each such account, a “Third-Party Account”) by either: (1) providing your Third-Party Account login information through the Site; or (2) allowing us to access your Third-Party Account, as is permitted under the applicable terms and conditions that govern your use of each Third-Party Account.

You represent and warrant that you are entitled to disclose your Third-Party Account login information to us and/or grant us access to your Third-Party Account, without breach by you of any of the terms and conditions that govern your use of the applicable Third-Party Account, and without obligating us to pay any fees or making us subject to any usage limitations imposed by the third-party service provider of the Third-Party Account.

By granting us access to any Third-Party Accounts, you understand that (1) we may access, make available, and store (if applicable) any content that you have provided to and stored in your Third-Party Account (the “Social Network Content”) so that it is available on and through the Site via your account, including without limitation any friend lists and (2) we may submit to and receive from your Third-Party Account additional information to the extent you are notified when you link your account with the Third-Party Account.

Depending on the Third-Party Accounts you choose and subject to the privacy settings that you have set in such Third-Party Accounts, personally identifiable information that you post to your Third-Party Accounts may be available on and through your account on the Site.

Please note that if a Third-Party Account or associated service becomes unavailable or our access to such Third-Party Account is terminated by the third-party service provider, then Social Network Content may no longer be available on and through the Site. You will have the ability to disable the connection between your account on the Site and your Third-Party Accounts at any time.

PLEASE NOTE THAT YOUR RELATIONSHIP WITH THE THIRD-PARTY SERVICE PROVIDERS ASSOCIATED WITH YOUR THIRD-PARTY ACCOUNTS IS GOVERNED SOLELY BY YOUR AGREEMENT(S) WITH SUCH THIRD-PARTY SERVICE PROVIDERS.

We make no effort to review any Social Network Content for any purpose, including but not limited to, for accuracy, legality, or non-infringement, and we are not responsible for any Social Network Content.

You acknowledge and agree that we may access your email address book associated with a Third-Party Account and your contacts list stored on your mobile device or tablet computer solely for purposes of identifying and informing you of those contacts who have also registered to use the Site.

You can deactivate the connection between the Site and your Third-Party Account by contacting us using the contact information below or through your account settings (if applicable). We will attempt to delete any information stored on our servers that was obtained through such Third-Party Account, except the username and profile picture that become associated with your account.

SUBMISSIONS

You acknowledge and agree that any questions, comments, suggestions, ideas, feedback, or other information regarding the Site (“Submissions”) provided by you to us are non-confidential and shall become our sole property. We shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of these Submissions for any lawful purpose, commercial or otherwise, without acknowledgment or compensation to you.

You hereby waive all moral rights to any such Submissions, and you hereby warrant that any such Submissions are original with you or that you have the right to submit such Submissions. You agree there shall be no recourse against us for any alleged or actual infringement or misappropriation of any proprietary right in your Submissions.

THIRD-PARTY WEBSITES AND CONTENT

The Site may contain (or you may be sent via the Site) links to other websites (“Third-Party Websites”) as well as articles, photographs, text, graphics, pictures, designs, music, sound, video, information, applications, software, and other content or items belonging to or originating from third parties (“Third-Party Content”).

Such Third-Party Websites and Third-Party Content are not investigated, monitored, or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Third-Party Websites accessed through the Site or any Third-Party Content posted on, available through, or installed from the Site, including the content, accuracy, offensiveness, opinions, reliability, privacy practices, or other policies of or contained in the Third-Party Websites or the Third-Party Content.

Inclusion of, linking to, or permitting the use or installation of any Third-Party Websites or any Third-Party Content does not imply approval or endorsement thereof by us. If you decide to leave the Site and access the Third-Party Websites or to use or install any Third-Party Content, you do so at your own risk, and you should be aware these Terms and Conditions no longer govern.

You should review the applicable terms and policies, including privacy and data gathering practices, of any website to which you navigate from the Site or relating to any applications you use or install from the Site. Any purchases you make through Third-Party Websites will be through other websites and from other companies, and we take no responsibility whatsoever in relation to such purchases which are exclusively between you and the applicable third party.

You agree and acknowledge that we do not endorse the products or services offered on Third-Party Websites and you shall hold us harmless from any harm caused by your purchase of such products or services. Additionally, you shall hold us harmless from any losses sustained by you or harm caused to you relating to or resulting in any way from any Third-Party Content or any contact with Third-Party Websites.

ADVERTISERS

We allow advertisers to display their advertisements and other information in certain areas of the Site, such as sidebar advertisements or banner advertisements. If you are an advertiser, you shall take full responsibility for any advertisements you place on the Site and any services provided on the Site or products sold through those advertisements.

Further, as an advertiser, you warrant and represent that you possess all rights and authority to place advertisements on the Site, including, but not limited to, intellectual property rights, publicity rights, and contractual rights.

[As an advertiser, you agree that such advertisements are subject to our Digital Millennium Copyright Act (“DMCA”) Notice and Policy provisions as described below, and you understand and agree there will be no refund or other compensation for DMCA takedown-related issues.] We simply provide the space to place such advertisements, and we have no other relationship with advertisers.

SITE MANAGEMENT

We reserve the right, but not the obligation, to:

(1) monitor the Site for violations of these Terms and Conditions;

(2) take appropriate legal action against anyone who, in our sole discretion, violates the law or these Terms and Conditions, including without limitation, reporting such user to law enforcement authorities;

(3) in our sole discretion and without limitation, refuse, restrict access to, limit the availability of, or disable (to the extent technologically feasible) any of your Contributions or any portion thereof;

(4) in our sole discretion and without limitation, notice, or liability, to remove from the Site or otherwise disable all files and content that are excessive in size or are in any way burdensome to our systems;

(5) otherwise manage the Site in a manner designed to protect our rights and property and to facilitate the proper functioning of the Site.

PRIVACY POLICY

We care about data privacy and security. Please review our Privacy Policy [CLICK HERE]/posted on the Site]. By using the Site, you agree to be bound by our Privacy Policy, which is incorporated into these Terms and Conditions. Please be advised the Site is hosted in the United States.

If you access the Site from the European Union, Asia, or any other region of the world with laws or other requirements governing personal data collection, use, or disclosure that differ from applicable laws in the United States, then through your continued use of the Site, you are transferring your data to the United States, and you expressly consent to have your data transferred to and processed in the United States.

[Further, we do not knowingly accept, request, or solicit information from children or knowingly market to children. Therefore, in accordance with the U.S. Children’s Online Privacy Protection Act, if we receive actual knowledge that anyone under the age of 13 has provided personal information to us without the requisite and verifiable parental consent, we will delete that information from the Site as quickly as is reasonably practical.]

DIGITAL MILLENNIUM COPYRIGHT ACT (DMCA) NOTICE AND POLICY

Notifications

We respect the intellectual property rights of others. If you believe that any material available on or through the Site infringes upon any copyright you own or control, please immediately notify our Designated Copyright Agent using the contact information provided below (a “Notification”).

A copy of your Notification will be sent to the person who posted or stored the material addressed in the Notification. Please be advised that pursuant to federal law you may be held liable for damages if you make material misrepresentations in a Notification. Thus, if you are not sure that material located on or linked to by the Site infringes your copyright, you should consider first contacting an attorney.

All Notifications should meet the requirements of DMCA 17 U.S.C. § 512(c)(3) and include the following information:

(1) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;

(2) identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works on the Site are covered by the Notification, a representative list of such works on the Site;

(3) identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material;

(4) information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number, and, if available, an email address at which the complaining party may be contacted;

(5) a statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law;

(6) a statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed upon.

Counter Notification

If you believe your own copyrighted material has been removed from the Site as a result of a mistake or misidentification, you may submit a written counter notification to [us/our Designated Copyright Agent] using the contact information provided below (a “Counter Notification”).

To be an effective Counter Notification under the DMCA, your Counter Notification must include substantially the following:

(1) identification of the material that has been removed or disabled and the location at which the material appeared before it was removed or disabled;

(2) a statement that you consent to the jurisdiction of the Federal District Court in which your address is located, or if your address is outside the United States, for any judicial district in which we are located;

(3) a statement that you will accept service of process from the party that filed the Notification or the party’s agent;

(4) your name, address, and telephone number;

(5) a statement under penalty of perjury that you have a good faith belief that the material in question was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled;

(6) your physical or electronic signature.

If you send us a valid, written Counter Notification meeting the requirements described above, we will restore your removed or disabled material, unless we first receive notice from the party filing the Notification informing us that such party has filed a court action to restrain you from engaging in infringing activity related to the material in question.

Please note that if you materially misrepresent that the disabled or removed content was removed by mistake or misidentification, you may be liable for damages, including costs and attorney’s fees. Filing a false Counter Notification constitutes perjury.

Designated Copyright Agent

[Name]

Attn: Copyright Agent

[Address]

[City, State Zip]

[email]

COPYRIGHT INFRINGEMENTS

We respect the intellectual property rights of others. If you believe that any material available on or through the Site infringes upon any copyright you own or control, please immediately notify us using the contact information provided below (a “Notification”). A copy of your Notification will be sent to the person who posted or stored the material addressed in the Notification.

Please be advised that pursuant to federal law you may be held liable for damages if you make material misrepresentations in a Notification. Thus, if you are not sure that material located on or linked to by the Site infringes your copyright, you should consider first contacting an attorney.]

TERM AND TERMINATION

These Terms and Conditions shall remain in full force and effect while you use the Site. WITHOUT LIMITING ANY OTHER PROVISION OF THESE TERMS AND CONDITIONS, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SITE (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE TERMS AND CONDITIONS OR OF ANY APPLICABLE LAW OR REGULATION. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SITE OR DELETE [YOUR ACCOUNT AND] ANY CONTENT OR INFORMATION THAT YOU POSTED AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION.

If we terminate or suspend your account for any reason, you are prohibited from registering and creating a new account under your name, a fake or borrowed name, or the name of any third party, even if you may be acting on behalf of the third party.

In addition to terminating or suspending your account, we reserve the right to take appropriate legal action, including without limitation pursuing civil, criminal, and injunctive redress.

MODIFICATIONS AND INTERRUPTIONS

We reserve the right to change, modify, or remove the contents of the Site at any time or for any reason at our sole discretion without notice. However, we have no obligation to update any information on our Site. We also reserve the right to modify or discontinue all or part of the Site without notice at any time.

We will not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the Site.

We cannot guarantee the Site will be available at all times. We may experience hardware, software, or other problems or need to perform maintenance related to the Site, resulting in interruptions, delays, or errors.

We reserve the right to change, revise, update, suspend, discontinue, or otherwise modify the Site at any time or for any reason without notice to you. You agree that we have no liability whatsoever for any loss, damage, or inconvenience caused by your inability to access or use the Site during any downtime or discontinuance of the Site.

Nothing in these Terms and Conditions will be construed to obligate us to maintain and support the Site or to supply any corrections, updates, or releases in connection therewith.

GOVERNING LAW

These Terms and Conditions and your use of the Site are governed by and construed in accordance with the laws of the State of [name of state] applicable to agreements made and to be entirely performed within the State/Commonwealth of [name of state], without regard to its conflict of law principles.

DISPUTE RESOLUTION

Option 1: Any legal action of whatever nature brought by either you or us (collectively, the “Parties” and individually, a “Party”) shall be commenced or prosecuted in the state and federal courts located in [name of county] County, [name of state], and the Parties hereby consent to, and waive all defenses of lack of personal jurisdiction and forum non conveniens with respect to venue and jurisdiction in such state and federal courts.

Application of the United Nations Convention on Contracts for the International Sale of Goods and the Uniform Computer Information Transaction Act (UCITA) are excluded from these Terms and Conditions. In no event shall any claim, action, or proceeding brought by either Party related in any way to the Site be commenced more than ______ years after the cause of action arose.

Option 2: Informal Negotiations

To expedite resolution and control the cost of any dispute, controversy, or claim related to these Terms and Conditions (each a “Dispute” and collectively, the “Disputes”) brought by either you or us (individually, a “Party” and collectively, the “Parties”), the Parties agree to first attempt to negotiate any Dispute (except those Disputes expressly provided below) informally for at least ______ days before initiating arbitration. Such informal negotiations commence upon written notice from one Party to the other Party.

Binding Arbitration

If the Parties are unable to resolve a Dispute through informal negotiations, the Dispute (except those Disputes expressly excluded below) will be finally and exclusively resolved by binding arbitration. YOU UNDERSTAND THAT WITHOUT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL.

The arbitration shall be commenced and conducted under the Commercial Arbitration Rules of the American Arbitration Association (“AAA”) and, where appropriate, the AAA’s Supplementary Procedures for Consumer Related Disputes (“AAA Consumer Rules”), both of which are available at the AAA website www.adr.org.

Your arbitration fees and your share of arbitrator compensation shall be governed by the AAA Consumer Rules and, where appropriate, limited by the AAA Consumer Rules. [If such costs are determined by the arbitrator to be excessive, we will pay all arbitration fees and expenses.]

The arbitration may be conducted in person, through the submission of documents, by phone, or online. The arbitrator will make a decision in writing, but need not provide a statement of reasons unless requested by either Party.

The arbitrator must follow applicable law, and any award may be challenged if the arbitrator fails to do so. Except where otherwise required by the applicable AAA rules or applicable law, the arbitration will take place in [name of county] County, [name of state].

Except as otherwise provided herein, the Parties may litigate in court to compel arbitration, stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator.

If for any reason, a Dispute proceeds in court rather than arbitration, the Dispute shall be commenced or prosecuted in the state and federal courts located in [name of county] County, [name of state], and the Parties hereby consent to, and waive all defenses of lack of personal jurisdiction, and forum non conveniens with respect to venue and jurisdiction in such state and federal courts.

Application of the United Nations Convention on Contracts for the International Sale of Goods and the the Uniform Computer Information Transaction Act (UCITA) are excluded from these Terms and Conditions.

In no event shall any Dispute brought by either Party related in any way to the Site be commenced more than _____ years after the cause of action arose. If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.

Option 3: Binding Arbitration

To expedite resolution and control the cost of any dispute, controversy or claim related to these Terms and Conditions (each a “Dispute” and collectively, “Disputes”), any Dispute brought by either you or us (individually, a “Party” and collectively, the “Parties”) shall be finally and exclusively resolved by binding arbitration.

YOU UNDERSTAND THAT WITHOUT THIS PROVISION, YOU WOULD HAVE THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL. The arbitration shall be commenced and conducted under the Commercial Arbitration Rules of the American Arbitration Association (“AAA”) and, where appropriate, the AAA’s Supplementary Procedures for Consumer Related Disputes (“AAA Consumer Rules”), both of which are available at the AAA website www.adr.org.

Your arbitration fees and your share of arbitrator compensation shall be governed by the AAA Consumer Rules and, where appropriate, limited by the AAA Consumer Rules. [If such costs are determined to by the arbitrator to be excessive, we will pay all arbitration fees and expenses.]

The arbitration may be conducted in person, through the submission of documents, by phone, or online. The arbitrator will make a decision in writing, but need not provide a statement of reasons unless requested by either Party. The arbitrator must follow applicable law, and any award may be challenged if the arbitrator fails to do so.

Except where otherwise required by the applicable AAA rules or applicable law, the arbitration will take place in [name of county] County, [name of state]. Except as otherwise provided herein, the Parties may litigate in court to compel arbitration, stay proceedings pending arbitration, or to confirm, modify, vacate, or enter judgment on the award entered by the arbitrator.

If for any reason, a Dispute proceeds in court rather than arbitration, the Dispute shall be commenced or prosecuted in the state and federal courts located in [name of county] County, [name of state], and the Parties hereby consent to, and waive all defenses of lack of, personal jurisdiction, and forum non conveniens with respect to venue and jurisdiction in such state and federal courts.

Application of the United Nations Convention on Contracts for the International Sale of Goods and the Uniform Computer Information Transaction Act (UCITA) are excluded from these Terms and Conditions. In no event shall any Dispute brought by either Party related in any way to the Site or Services be commenced more than ______ years after the cause of action arose.

If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.

Option 2/Option 3: Restrictions

The Parties agree that any arbitration shall be limited to the Dispute between the Parties individually. To the full extent permitted by law, (a) no arbitration shall be joined with any other proceeding; (b) there is no right or authority for any Dispute to be arbitrated on a class-action basis or to utilize class action procedures; and (c) there is no right or authority for any Dispute to be brought in a purported representative capacity on behalf of the general public or any other persons.

Option 2/Option 3: Exceptions to [Informal Negotiations and] Arbitration

The Parties agree that the following Disputes are not subject to the above provisions concerning [informal negotiations and] binding arbitration: (a) any Disputes seeking to enforce or protect, or concerning the validity of, any of the intellectual property rights of a Party; (b) any Dispute related to, or arising from, allegations of theft, piracy, invasion of privacy, or unauthorized use; and (c) any claim for injunctive relief.

If this provision is found to be illegal or unenforceable, then neither Party will elect to arbitrate any Dispute falling within that portion of this provision found to be illegal or unenforceable and such Dispute shall be decided by a court of competent jurisdiction within the courts listed for jurisdiction above, and the Parties agree to submit to the personal jurisdiction of that court.

CORRECTIONS

There may be information on the Site that contains typographical errors, inaccuracies, or omissions that may relate to the Site, including descriptions, pricing, availability, and various other information. We reserve the right to correct any errors, inaccuracies, or omissions and to change or update the information on the Site at any time, without prior notice.

DISCLAIMER

THE SITE IS PROVIDED ON AN AS-IS AND AS-AVAILABLE BASIS. YOU AGREE THAT YOUR USE OF THE SITE AND OUR SERVICES WILL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE SITE AND YOUR USE THEREOF, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE MAKE NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE SITE’S CONTENT OR THE CONTENT OF ANY WEBSITES LINKED TO THE SITE AND WE WILL ASSUME NO LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT AND MATERIALS, (2) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SITE, (3) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SITE, (5) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SITE BY ANY THIRD PARTY, AND/OR (6) ANY ERRORS OR OMISSIONS IN ANY CONTENT AND MATERIALS OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SITE. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE SITE, ANY HYPERLINKED WEBSITE, OR ANY WEBSITE OR MOBILE APPLICATION FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND ANY THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.

AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.

##### **LIMITATIONS OF LIABILITY**

IN NO EVENT WILL WE OR OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SITE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

[NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, OUR LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO [THE LESSER OF] [THE AMOUNT PAID, IF ANY, BY YOU TO US DURING THE [_________] MONTH PERIOD PRIOR TO ANY CAUSE OF ACTION ARISING [OR] [$_________]. CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES.

IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.]

##### **INDEMNIFICATION**

You agree to defend, indemnify, and hold us harmless, including our subsidiaries, affiliates, and all of our respective officers, agents, partners, and employees, from and against any loss, damage, liability, claim, or demand, including reasonable attorneys’ fees and expenses, made by any third party due to or arising out of: (1) [your Contributions]; (2) use of the Site; (3) breach of these Terms and Conditions; (4) any breach of your representations and warranties set forth in these Terms and Conditions; (5) your violation of the rights of a third party, including but not limited to intellectual property rights; or (6) any overt harmful act toward any other user of the Site with whom you connected via the Site.

Notwithstanding the foregoing, we reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate, at your expense, with our defense of such claims. We will use reasonable efforts to notify you of any such claim, action, or proceeding which is subject to this indemnification upon becoming aware of it.

##### **USER DATA**

We will maintain certain data that you transmit to the Site for the purpose of managing the Site, as well as data relating to your use of the Site. Although we perform regular routine backups of data, you are solely responsible for all data that you transmit or that relates to any activity you have undertaken using the Site.

You agree that we shall have no liability to you for any loss or corruption of any such data, and you hereby waive any right of action against us arising from any such loss or corruption of such data.

##### **ELECTRONIC COMMUNICATIONS, TRANSACTIONS, AND SIGNATURES**

Visiting the Site, sending us emails, and completing online forms constitute electronic communications. You consent to receive electronic communications, and you agree that all agreements, notices, disclosures, and other communications we provide to you electronically, via email and on the Site, satisfy any legal requirement that such communication be in writing.

YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS, AND OTHER RECORDS, AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES, AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED BY US OR VIA THE SITE.

You hereby waive any rights or requirements under any statutes, regulations, rules, ordinances, or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by any means other than electronic means.

##### **CALIFORNIA USERS AND RESIDENTS**

If any complaint with us is not satisfactorily resolved, you can contact the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs in writing at 1625 North Market Blvd., Suite N 112, Sacramento, California 95834 or by telephone at (800) 952-5210 or (916) 445-1254.

##### **MISCELLANEOUS**

These Terms and Conditions and any policies or operating rules posted by us on the Site constitute the entire agreement and understanding between you and us. Our failure to exercise or enforce any right or provision of these Terms and Conditions shall not operate as a waiver of such right or provision.

These Terms and Conditions operate to the fullest extent permissible by law. We may assign any or all of our rights and obligations to others at any time. We shall not be responsible or liable for any loss, damage, delay, or failure to act caused by any cause beyond our reasonable control.

If any provision or part of a provision of these Terms and Conditions is determined to be unlawful, void, or unenforceable, that provision or part of the provision is deemed severable from these Terms and Conditions and does not affect the validity and enforceability of any remaining provisions.

There is no joint venture, partnership, employment or agency relationship created between you and us as a result of these Terms and Conditions or use of the Site. You agree that these Terms and Conditions will not be construed against us by virtue of having drafted them.

You hereby waive any and all defenses you may have based on the electronic form of these Terms and Conditions and the lack of signing by the parties hereto to execute these Terms and Conditions.

CONTACT US

In order to resolve a complaint regarding the Site or to receive further information regarding use of the Site, please contact us at:

[Corporate Name]

[Corporate Address]

[Corporate Phone Number]

[Corporate Fax Number]

[Email Address]`;

export const privacy = `##### **Privacy Policy**
Pantavanij Company Limited (the “**Company**”) realize the importance of the privacy and the personal data protection for the Company’s clients, customers, visitors of the website, applications or any system operated by the Company (collectively called as “you”). Thus, the Company has established the privacy policy in order to notify you about the Company’s process of collecting, using and disclosing the personal data, as well as, the rights for your personal data protection as prescribed by the applicable laws on personal data protection. This will enable you to confidently use website, applications or any system operated by the Company, including any and all services of the Company (collectively called as the “**Services**”).

##### **Personal Data**
“**Personal Data**” means the information relating to a person, which enables the identification of such person, whether directly or indirectly, but not including the information of the deceased persons in particular, such as name-surname, identification card number, address, telephone number, financial transaction.

Personal Data may consist of sensitive information and at risk of being treated unfairly (Sensitive Personal Data) such Personal Data includes but not limited to biometrics data, data relating to religious. 
In this regard, such Personal Data includes any information provided by you to the Company and/or being in the Company’s possession and/or lawfully collected by the Company from any other sources or any other persons.

In case where necessary for the Company to collect, use or disclose your Personal Data which is out of the scope as specified in this Privacy Policy, the Company will inform you regarding such different characteristics at the time or prior to the collection, use or disclosure of your Personal Data. 

By using the Services, it is considered that you have read and understood this Privacy Policy.

##### **Type of Personal Data Collected, Used or Disclosed by the Company**

* Information on identification card, passport and/or other evidence issued by government authorities such as identification card number, name, surname, name prefix;

* Necessary contact information such as contactable address, telephone number, e-mail;
* Particular personal characteristics such as status, biometrics data, voice recording data;
* Career information such as position;
* Financial information such as records of  sales transactions made through the Services, deposit account information;
* Information relating to your devices and usage behaviors, including but not limited to unique device identifier, IP address, mobile device operating systems, mobile network service provider, location, cookie;

Account login information and any information recorded from your access to the Services such as login ID, password, and/or security question and answer, profile picture, log file.For the necessity of providing additional services apart from fundamental Services or the collection, use, disclosure of Sensitive Personal Data other than those specified above, the Company will perform the processing under legal basis as prescribed by law only. In this regard, the Company will inform the purpose and type of Personal Data required to be collected, used or disclosed prior to or at the time of such processing.

##### **Basis of the Collection, Use and Disclosure of your Personal Data and the Purposes of such Processing**
The Company will collect, use or disclose your Personal Data under legal basis and in accordance with the following purposes:
* For necessity for the performance of the contract to which you are the contractual party, or for the performance in accordance with your request prior to entering into the contract, including but not limited to:

 * Consideration of account registration requests;

 * Any other necessities for providing the best Services from the Company;
 * Providing support service, contact and request for information, accept request, receiving news or to inquire about the Services;
 * Enhancing and improving the Services’ quality, increasing the Services efficiency, and facilitating you in using the Service;
 * Processing data in order to render the Services; and
 * Any other processing related to the Services and possibly benefiting you. 
* For compliance with the laws, including but not limited to:
 * To Comply with relevant laws in which the Company is subjected to, in compliance with laws, regulations, rules, codes of practice or guidelines issued by authorities or regulatory agencies. In this regard, the Company may transfer your Personal Data to internal/external auditors, government agencies or other related juristic persons.
* Consent, including but not limited to:
 * Marketing purposes such as offering privileges and/or any products or services that may interest you, promotional campaigns, public relations, doing surveys in connection with the Services, including doing statistic, analysis, study and research, assessment of the information, or to manage the business needs of the Company, business partners or affiliated companies, through contact channels that you have provided such as e-mail; and
 * other legitimate purposes in which the Company has obtained consent from time to time such as to facilitate you in using the service of other service providers via the website, application or any system operated by the Company . 
* For legitimate interests of the Company or any other person other than the Company, except that such interests are overridden by the fundamental rights of your Personal Data, including but not limited:
 * Prevention of crime and fraud; and
 * Enabling security systems and networks to meet international standards.
* For substantial public interest which the Company has provided suitable measures to protect your fundamental rights and interest, including but not limited to:
 * Identification/verification of the identity in order to prevent crime and fraud; and
 * Suspicious of financial support for terrorism or money laundering.
Apart from the abovementioned legal basis and purposes, the Company may collect, use or disclose your personal under other legal basis, such as preventing or suppressing a danger to your life, body or health, or the archives for public interest. Where the collection, use or disclosure falls under other purposes in accordance with the mentioned basis, the Company will notify you afterward. 

##### **The Disclosure of Your Personal Data to Third Parties and the Collection of Personal Data from Other Sources.**
For the processing pursuant to the purposes under abovementioned legal basis. The Company may collect from and/or use, send, transfer, process and/or disclose the Personal Data to the following persons:
* Juristic persons having control over the Company or under the control of the Company including other companies under the same control of the Company, or other juristic persons or persons in which the Company is a contractual party, or having the legal relationship with the Company, including other service providers having power in making decision to take any action related to your Personal Data both within and outside the country such as external service providers, cloud service providers or other business partners of the Company. In this regard, the Company shall ensure that those service providers will process your Personal Data in accordance with this Privacy Policy and the applicable laws;
* The auditors, external examiners of the Company, government authorities, transferee of the right of claim, and any other persons or juristic persons that the Company is required to transfer the Personal Data as necessary to comply with the laws; and
* Business/enterprise transferee in case the Company has merged, transfers, sells its assets and/or business whether entirely or partially.

##### **Retention Period for Your Personal Data**
It is necessary for the Company to retain your Personal Data for as long as necessary throughout the time you are still using the Services or having the relationship with the Company, or as long as necessary to achieve the purposes related to the Company's Services. In this regard, the Company may continually retain such Personal Data in accordance with the laws, or for the purpose of verification and investigation in the event of dispute within the prescription as specified by law, for the period not exceeding 10 years.

However, the Company will delete or destroy your Personal Data, or make such Personal Data unidentifiable when it is no longer necessary to be retained or such retention period has ended.

##### **Security**
The Company acknowledges and realizes the importance of your Personal Data. Thus, the Company has improved and developed the security systems for your Personal Data in corresponding to the laws, and up-to-date with safety in accordance with the international standard at all time. The Company will proceed at its full effort to comply with this Privacy Policy, and will urge the Company’s personnel, including data processors, who are entitled to access the Personal Data or has legal duty, to keep and respect your Personal Data security.

In case the Company is necessary to transfer any of your Personal Data to foreign country, the Company will apply the standard as prescribed by the laws on personal data protection. Additionally, the Company will not transfer your Personal Data to the destination country that has no personal data protection standard sufficiently in accordance with the criteria as prescribed by the laws, except that you consent the Company to send or transfer your Personal Data to such destination country. However, in case of computer espionage resulting that your Personal Data has been stolen, whether by ways of hacking, stealing, copying or destroying database, destroying personal code (password mining) or any other methods, without the Company’s fault, in such circumstance, the Company will have the right to disclaim any liability resulting from such act.

##### **Your Rights**
You have the rights as follows:
* To request for accessing your own personal data held by the Company, and to request for obtaining the copy of personal data related to you, or to request for the disclosure regarding the acquisition of personal data that you did not give the consent;

* To request for obtaining your own personal data in normal readable or usable form by the device or equipment automatically operating, or for using or disclosing such personal data by automatic method (in case of preparing by the Company), or to request the Company to send or transfer such personal data to any other personal data controller as prescribed by the laws, and including to request for obtaining your own personal data that the Company has sent or transferred to any other personal data controller, (except that it cannot technically be done);
* To oppose the collection, usage or disclosure of your personal data as prescribed by the laws;
* To request the Company to delete, destroy, temporarily suspend the usage, or convert the personal data into the form of non-personally identifiable information; 
* To request the Company to suspend the usage of your personal data;
* To request the Company to amend or add the personal data to be accurate, up-to-date, complete, and not causing any misunderstandings;
In this regard, the Company will have the right to amend any inaccurate personal data that you used or presented to the Company for obtaining the Services, after the Company has received the accurate personal data together with the supporting evidence. This will be at the Company’s discretion;
* In case you wish to cancel the Services, then, you can revoke the consent given to the Company in accordance with the method as specified by the Company. Such revocation of consent will not affect the collection, usage or disclosure of the personal data that you have already given the consent;
* To file the complaint with the authorities, for the case that the Company does not comply with the Privacy Policy.
However, you acknowledge that such rights are the basic rights. You may exercise such rights in accordance with the provisions of the applicable laws. Additionally, the Company, being as the said personal data controller, is entitled to reject your exercising of such rights.

If you exercise any of your rights under data protection law, the Company shall respond promptly and shall put our best effort to process such request, free of charge, within one calendar month after receiving all required supporting documents. Please be aware that the Company might charge a reasonable fee for complex, unfounded, excessive or repetitive request.


##### **Personal Data of Minors**
The Company will collect, use or disclose the Personal Data of minors only in accordance with the standard as prescribed by the laws. In case the Company is aware of the import of minors’ Personal Data into the Company’s system, the Company shall take the appropriate action to rapidly manage such data.

##### **Language**
The translation of this Privacy Policy, whether in any language whatsoever, is for your convenience only, without any intention to change this Privacy Policy. In case of any discrepancy between Thai version and any other languages version, the Thai version shall prevail.

##### **Contact**
Should you have any question, complaint, request to access, or query regarding this Privacy Policy and/or would like to examine any of your Personal Data in possession of the Company. You can contact via:

###### **Customer Care**

Address 	:1168/94, Lumpini Tower 31st Floor, Rama IV Road, Tungmahamek Sub-District, Sathon District, Bangkok 10120
Telephone	: 0-2034-4333

Facsimile	: 0-2679-7474

Email		: customercare@pantavanij.com 

###### **Data Protection Officer (DPO)**
Address	: .................

Telephone	: .................

Email		: ................

or any other channels as specified by the Company.

##### **Improvement of Policy**
Using any Services of the Company shall be deemed as the acceptance of this Privacy Policy. The Company may make amendment to this Privacy Policy at any time, and notify you of such amendment. Using the website, applications or any system operated by the Company or any Services continually after the notification of such amendment will be deemed as acceptance of the amendment for each time. `;

export const tcTH = `##### **เงื่อนไขการรับสิทธิพิเศษลูกค้าทรู**
* สำหรับลูกค้าจดทะเบียนในนามบุคคลธรรมดา (individual) เท่านั้น

* สำหรับลูกค้าที่ใช้สินค้า/บริการในกลุ่มทรูอย่างน้อย 1 สินค้า (ทรูมูฟ เอช หรือ ทรูออนไลน์ หรือ ทรูวิชั่นส์) และยังคงสถานะการใช้บริการปกติ (Active)

* มียอดชำระค่าใช้บริการเฉลี่ยจากทุกสินค้า/บริการ (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ตามเกณฑ์ที่กำหนดและยังคงสถานะการใช้บริการปกติ (Active) ภายใต้หมายเลขบัตรประชาชน/พาสปอร์ต เดียวกัน

* ยอดชำระค่าสินค้า/บริการที่นำมาคำนวณในการจัดสถานะ คือ ยอดเฉลี่ยจากสินค้า/บริการ ที่มีสถานะปกติ (Active) เท่านั้น

* ลูกค้ามีประวัติการชำระค่าสินค้า/บริการตรงตามกำหนดในทุกสินค้า/บริการ โดยไม่มีประวัติการถูกระงับใช้บริการ

* สิทธิพิเศษลูกค้าทรู มีสถานะ 1 เดือนนับจากวันที่ระบบออกบัตรทรูการ์ดให้ (วันที่หมดอายุหน้าบ้ตร คือ วันหมดอายุของบัตรทรูการ์ด)

* สถานะของลูกค้าทรู จะมีการจัดสถานะทุก 1 เดือนปฏิทิน

* กรณียอดชำระค่าสินค้า/บริการที่นำมาคำนวนในการจัดสถานะลูกค้าทรู เป็นยอดเฉลี่ยจากสินค้า/บริการที่มีสถานะปกติ (Active) ลดลง มีผลให้สถานะของลูกค้าทรูลดลง ระบบจะคงสถานะลูกค้าทรูเดิมต่อไปเป็นระยะเวลา 6 เดือน แต่ในระหว่างนี้หากยอดชำระค่าสินค้า/บริการดังกล่าวเพิ่มขึ้น สถานะลูกค้าทรูจะเปลี่ยนแปลงสถานะตามเงื่อนไขของการจัดสถานะนั้นๆ

* สำหรับลูกค้าต่างชาติ ยอดชำระค่าบริการสินค้า/บริการที่นำมาคำนวณในการจัดสถานะลูกค้าทรูจะต้องเป็นสินค้า/บริการที่จดทะเบียนภายใต้หมายเลขบัตรประชาชน/พาสปอร์ต เดียวกันเท่านั้น

##### **ลูกค้าทรูแบล็ค**

* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาติดต่อกันมากกว่า 10 ปี และยังคงสถานะการใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ระหว่าง 1,500 บาท ถึง 1,999 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)

* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาติดต่อกันมากกว่า 5 ปี และยังคงสถานะใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ระหว่าง 2,000 บาท ถึง 2,999 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)

* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาตั้งแต่ 1 วันขึ้นไปและยังคงสถานะการใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลังมากกว่า 3,000 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)

* ลูกค้าทรูวิชั่นส์ที่ใช้บริการแพ็กเกจ Platinum HD (Stand Alone หรือ True Convergence) ได้รับสถานะทรูแบล็ค นาน 12 เดือน

##### **ลูกค้าทรูเรด**

* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาติดต่อกันมากกว่า 10 ปี และยังคงสถานะการใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ระหว่าง 600 บาท ถึง 999 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)

* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาติดต่อกันมากกว่า 2 ปี และยังคงสถานะการใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ระหว่าง 1,000 บาท ถึง 1,499 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)
* ลูกค้าทรูที่ใช้สินค้าและบริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาติดต่อกันมากกว่า 1 ปี แต่น้อยกว่า 10 ปี และยังคงสถานะใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ระหว่าง 1,500 บาท ถึง 1,999 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)
* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาตั้งแต่ 1 วัน ถึง 5 ปี และยังคงสถานะการใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ระหว่าง 2,000 บาท ถึง 2,999 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)
* ลูกค้าทรูวิชั่นส์ที่ใช้บริการแพ็กเกจ Gold HD (Stand Alone) ได้รับสถานะทรูเรด นาน 12 เดือน

##### **ลูกค้าทรูบลู**
* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาติดต่อกันมากกว่า 5 ปี และยังคงสถานะการใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ระหว่าง 250 บาท ถึง 599 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)
* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาติดต่อกันมากกว่า 1 ปี แต่น้อยกว่า 10 ปี และยังคงสถานะการใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลังระหว่าง 600 บาท ถึง 999 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)
* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาติดต่อกันตั้งแต่ 1 วัน ถึง 2 ปี และยังคงสถานะการใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ระหว่าง 1,000 บาท ถึง 1,499 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)
* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาติดต่อกันตั้งแต่ 1 วัน ถึง 1 ปี และยังคงสถานะการใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ระหว่าง 1,500 บาท ถึง 1,999 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)

##### **ลูกค้าทรูกรีน**
* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาตั้งแต่ 1 วัน ถึง 5 ปี และยังคงสถานะการใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ระหว่าง 250 บาท ถึง 599 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)
* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) ระยะเวลาตั้งแต่ 1 วัน ถึง 1 ปี และยังคงสถานะใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ระหว่าง 600 บาท ถึง 999 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)

##### **ลูกค้าทรูไวท์**

* ลูกค้าทรูที่ใช้สินค้า/บริการในกลุ่มทรู (ทรูมูฟ เอช, ทรูออนไลน์, ทรูวิชั่นส์) และยังคงสถานะการใช้บริการปกติ (Active) โดยมียอดค่าชำระสินค้า/บริการรวมกันเฉลี่ย 6 เดือนย้อนหลัง ไม่เกิน 250 บาทต่อเดือน (กรณีที่ลูกค้าใช้บริการน้อยกว่า 6 เดือน ให้เฉลี่ยตามจำนวนเดือนที่ใช้บริการ)

##### **ข้อกำหนดและเงื่อนไขในการรับสิทธิ์อัปสปีดทรูออนไลน์ หรือรับทรูพอยท์**
การรับสิทธิพิเศษเพิ่มเติมสำหรับผู้ใช้บริการปัจจุบัน ทรูออนไลน์ โทรศัพท์เคลื่อนที่ ทรูมูฟ เอช และ/หรือ ทรูวิชั่นส์ โดยบริษัท ทรู อินเทอร์เน็ต คอร์ปอเรชั่น จำกัด บริษัท ทรู มูฟ เอช ยูนิเวอร์แซล คอมมิวนิเคชั่น และ/หรือ บริษัท ทรู วิชั่นส์ กรุ๊ป จำกัด (รวมเรียกว่า "บริษัทฯ")
1. ข้อกำหนดและเงื่อนไขการรับสิทธิพิเศษ เพิ่มความเร็วอินเทอร์เน็ตบ้าน
 1. ผู้ใช้บริการมีความประสงค์ขอรับสิทธิพิเศษจากการใช้บริการทรูออนไลน์ ดังนี้
บริการทรูออนไลน์: รับสิทธิ์เพิ่มความเร็วอินเทอร์เน็ตบ้านไฟเบอร์ โดยมีความเร็วสูงสุด 1000/1000 Mbps เฉพาะพื้นที่ โครงข่ายFTTH ที่พร้อมให้บริการเท่านั้น (โดยแต่ละระดับความเร็วเป็นไปตามระดับของทรูการ์ดของลูกค้า) เป็นระยะเวลานาน 30 วันจากวันที่กดรับสิทธิ์ โดยสามารถกดรับสิทธิ์ได้สูงสุด 12 ครั้งต่อปี โดยรายละเอียดของแต่ละประเภททรูการ์ดแบ่งเป็น
ลูกค้าทรูแบล็ค รับสิทธิ์เพิ่มความเร็วอินเทอร์เน็ตบ้านไฟเบอร์ โดยมีความเร็วสูงสุด 1000/1000 Mbps (หากลูกค้าไม่สามารถรับสิทธิ์์ได้ เนื่องจากเทคโนโลยีไม่รองรับ หรือ พื้นที่ไม่รองรับ หรือ ลูกค้ามีบริการเสริมอย่างอื่นจะได้รับสิทธิ์ทรูพอยท์ 30 ทรูพอยท์ ทดแทน)
ลูกค้าทรูเรด รับสิทธิ์เพิ่มความเร็วอินเทอร์เน็ตบ้านไฟเบอร์ โดยมีความเร็วสูงสุด 500/500 Mbps (หากลูกค้าไม่สามารถรับสิทธิ์ได้ เนื่องจากเทคโนโลยีไม่รองรับ หรือ พื้นที่ไม่รองรับ หรือ ลูกค้ามีบริการเสริมอย่างอื่น จะได้รับสิทธิ์ทรูพอยท์ 30 ทรูพอยท์ ทดแทน)
ลูกค้าทรูบลู ทรูกรีน และทรูไวท์ จะไม่ได้รับสิทธิ์ เพิ่มความเร็วอินเทอร์เน็ตบ้านไฟเบอร์
 2. ผู้ใช้บริการจะได้รับสิทธิพิเศษตามข้อ 1 ส่วนของ (1) ข้างต้นเมื่อมีการใช้งานเบอร์มือถือทรูมูฟ เอช อย่างน้อย 1 เบอร์ และสถานะของการใช้บริการได้ตามปกติ (Active Status) โดยชำระค่าบริการทุกบริการอย่างครบถ้วน และสามารถรับสิทธิ์ผ่าน TrueID ที่ Login เข้าระบบด้วยเบอร์มือถือทรูมูฟ เอช เท่านั้น
 3. ผู้ใช้บริการจะได้รับสิทธิพิเศษข้างต้น เมื่อมีสถานะของการใช้บริการได้ตามปกติ (Active Status) โดยชำระค่าบริการทุกบริการอย่างครบถ้วน
 4. ผู้ใช้บริการสามารถใช้สิทธิพิเศษตามข้อ 1 ส่วนของ (1) ข้างต้น นับตั้งแต่วันที่ติดตั้งสำเร็จ และใช้งานแพ็กเกจ ราคา 599 บาท ขึ้นไป
 5. สิทธิพิเศษข้างต้นนี้ ไม่สามารถแลก คืน หรือเปลี่ยนเป็นเงินสด หรือของอื่นใดได้ และไม่สามารถใช้ร่วมกับรายการส่งเสริมการขายหรือข้อเสนออื่นได้
 6. บริษัทฯ มีสิทธิ์เปลี่ยนแปลง หรือยกเลิกการให้สิทธิพิเศษ ในเวลาใดๆ ก็ได้ โดยไม่ต้องแจ้งให้ผู้ใช้บริการทราบล่วงหน้า หากมีข้อกำหนด คำสั่ง หรือนโยบายของหน่วยงานของรัฐที่เกี่ยวข้อง กำหนดให้มีการแก้ไข เปลี่ยนแปลง ระงับ หรือยกเลิกเงื่อนไขการให้บริการใดๆ ที่เกี่ยวของกับการให้สิทธิพิเศษอันเป็นการเพิ่มภาระในการดำเนินการของบริษัทฯ เว้นแต่จะได้มีการกำหนดเงื่อนไขโดยชัดแจ้งเป็นอย่างอื่น ทั้งนี้ นอกเหนือจากการดำเนินการข้างต้นแล้ว บริษัทฯ มีสิทธิ์แก้ไข เปลี่ยนแปลง ระงับ หรือยกเลิกเงื่อนไขการให้สิทธิพิเศษได้ตามที่บริษัทฯ เห็นว่าเหมาะสม โดยจะได้แจ้งให้ผู้ใช้บริการทราบล่วงหน้าผ่านช่องทางที่บริษัทฯ เห็นสมควร
 7. ความเร็วสำหรับบริการอินเทอร์เน็ตบ้าน อาจมีการเปลี่ยนแปลง หรือมีความเร็วไม่เท่ากับความเร็วที่ได้รับตามใบรับสิทธิพิเศษฉบับนี้ โดยขึ้นอยู่กับปัจจัยต่าง ๆ ที่เกี่ยวข้อง เช่น สายโทรศัพท์ภายในของสมาชิก เครื่องคอมพิวเตอร์ เครื่องโทรศัพท์เคลื่อนที่ อุปกรณ์เซิร์ฟเวอร์และ Router ของเว็บไซต์ที่ผู้ใช้บริการเข้าเยี่ยมชม
 8. สิทธิพิเศษเพิ่มความเร็วบริการอินเทอร์เน็ตบ้านที่ความเร็วสูงสุด 500/500 และ 1000/1000 Mbps ผู้ใช้บริการจะต้องอยู่ในพื้นที่ที่เทคโนโลยีไฟเบอร์ออฟติก(FTTH) ครอบคลุมพื้นที่ที่ใช้งาน และใช้งานแพ็กเกจตั้งแต่ราคา 599 บาท ขึ้นไป และกรณีลูกค้าใช้บริการใน Package ตระกูลสุข ได้แก่ Sook2 และ Sook3 จะต้องดำเนินการปลี่ยน Profile เป็น True Super Fiber ก่อนจึงจะสามารถรับสิทธิ์ได้
 9. ความเร็วสำหรับบริการอินเทอร์เน็ตบ้าน อาจมีการเปลี่ยนแปลง หรือมีความเร็วไม่เท่ากับความเร็วที่ได้รับตามใบรับสิทธิพิเศษฉบับนี้ โดยขึ้นอยู่กับปัจจัยต่าง ๆ ที่เกี่ยวข้อง เช่น สายโทรศัพท์ภายในของสมาชิก เครื่องคอมพิวเตอร์ อุปกรณ์เซิร์ฟเวอร์และ Router รวมถึงองค์ประกอบต่าง ๆ ของเว็บไซต์ที่ผู้ใช้บริการเข้าเยี่ยมชม
 10. สิทธิพิเศษข้างต้นนี้ ไม่สามารถรับสิทธิ์ ซ้ำ หรือซ้อนกันกับรายการส่งเสริมการขายอื่นๆ ได้
 11. ข้อกำหนดและเงื่อนไขการใช้บริการทรูออนไลน์ เป็นไปตามที่กำหนดในคำขอ/สัญญาใช้บริการในกลุ่มทรู และ/หรือ ที่บริษัทฯ ผู้ให้บริการกำหนด
 12. ผู้ใช้บริการได้อ่านและเข้าใจ และตกลงยอมรับข้อกำหนดและเงื่อนไขที่ระบุไว้ข้างต้นโดยตลอดแล้วก่อนกดตอบรับรับสิทธิพิเศษตามช่องทางที่บริษัทฯ กำหนด`;

export const privacyTH = `##### **นโยบายการคุ้มครองข้อมูลส่วนบุคคล**
บริษัท พันธวณิช จำกัด (“**บริษัท**”) ตระหนักถึงความสําคัญในความเป็นส่วนตัวและการคุ้มครองข้อมูลส่วนบุคคลของลูกค้า ผู้ใช้บริการ ผู้เยี่ยมชมเว็บไซต์ แอปพลิเคชัน หรือระบบของบริษัท (รวมเรียกว่า “ท่าน”)  บริษัทจึงได้จัดให้มีนโยบายการคุ้มครองข้อมูลส่วนบุคคล เพื่อแจ้งให้ท่านทราบเกี่ยวกับแนวทางปฏิบัติของบริษัทในการเก็บรวบรวม ใช้ และเปิดเผยข้อมูลส่วนบุคคล รวมถึงสิทธิต่าง ๆ ที่ท่านจะได้รับความคุ้มครองในส่วนของข้อมูลส่วนบุคคลตามกฎหมายที่เกี่ยวกับการคุ้มครองข้อมูลส่วนบุคคลได้กำหนดไว้ เพื่อให้ท่านสามารถใช้เว็บไซต์ แอปพลิเคชัน หรือระบบที่ดำเนินการโดยบริษัทและบริการใด ๆ ทั้งหมดของบริษัท (รวมเรียกว่า “**บริการ**”) ได้อย่างมั่นใจ

##### **ข้อมูลส่วนบุคคล**
ข้อมูลส่วนบุคคล หมายถึง ข้อมูลเกี่ยวกับบุคคลซึ่งสามารถระบุตัวบุคคลนั้นได้ ไม่ว่าทางตรงหรือทางอ้อม แต่ไม่รวมถึงข้อมูลของผู้ถึงแก่กรรมโดยเฉพาะ เช่น ชื่อ-นามสกุล เลขบัตรประชาชน ที่อยู่ หมายเลขโทรศัพท์ ข้อมูลทางการเงิน เป็นต้น

ข้อมูลส่วนบุคคลอาจประกอบด้วยข้อมูลที่มีความละเอียดอ่อนและเสี่ยงต่อการถูกใช้ในการเลือกปฏิบัติอย่างไม่เป็นธรรม (Sensitive Personal Data) ซึ่งข้อมูลส่วนบุคคลดังกล่าว รวมถึงแต่ไม่จำกัดอยู่เพียง ข้อมูลทางชีวภาพ ข้อมูลเกี่ยวกับศาสนา 
ทั้งนี้ ข้อมูลส่วนบุคคล รวมถึงข้อมูลใด ๆ ของท่านที่ได้ให้ไว้แก่บริษัท และ/หรือที่อยู่ในความครอบครองของบริษัท และ/หรือที่บริษัทเก็บรวบรวมจากแหล่งอื่นหรือบุคคลอื่นใดโดยถูกต้องตามกฎหมาย

ในกรณีที่บริษัทมีความจำเป็นที่จะต้องเก็บรวบรวม ใช้ หรือ เปิดเผยข้อมูลส่วนบุคคลของท่าน แตกต่างไปจากที่ระบุในนโยบายการคุ้มครองข้อมูลส่วนบุคคลนี้ บริษัทจะแจ้งให้ท่านทราบถึงลักษณะที่แตกต่างออกไปขณะหรือก่อนที่มีการเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลของท่าน
การที่ท่านเข้าใช้บริการ ให้ถือว่าท่านได้อ่านและเข้าใจในนโยบายการคุ้มครองข้อมูลส่วนบุคคลนี้แล้ว

##### **ประเภทของข้อมูลส่วนบุคคลที่บริษัทเก็บรวบรวม ใช้ หรือเปิดเผย**
* ข้อมูลตามบัตรประชาชน หนังสือเดินทาง และ/หรือหลักฐานอื่นที่ออกโดยราชการ เช่น เลขประจำตัวประชาชน ชื่อ นามสกุล คำนำหน้าชื่อ 
* ข้อมูลที่จำเป็นในการติดต่อท่าน เช่น ที่อยู่ที่สามารถติดต่อได้ หมายเลขโทรศัพท์เคลื่อนที่ อีเมล
* ลักษณะเฉพาะของบุคคล เช่น สถานภาพ ข้อมูลชีวภาพ (Biometrics) ข้อมูลบันทึกเสียงสนทนาทางโทรศัพท์
* ข้อมูลเกี่ยวกับการทำงาน เช่น ตำแหน่งงาน
* ข้อมูลเกี่ยวกับสถานะทางการเงิน เช่น บันทึกรายการธุรกรรมซื้อขายผ่านระบบของบริษัท ข้อมูลบัญชีเงินฝาก
* ข้อมูลเกี่ยวกับอุปกรณ์และพฤติกรรมการใช้บริการของท่าน รวมถึงแต่ไม่จำกัดเพียง หมายเลขประจำเครื่อง (Unique Device Identifier) และหมายเลขที่ใช้สำหรับระบุตัวตนของอุปกรณ์ที่เชื่อมต่ออยู่บนเครือข่าย             (IP address) ข้อมูลเกี่ยวกับระบบปฏิบัติการอุปกรณ์เคลื่อนที่ ผู้ให้บริการเครือข่ายโทรศัพท์เคลื่อนที่ ตำแหน่งที่อยู่ คุกกี้(cookie)
* ข้อมูลบัญชีการเข้าใช้งาน และข้อมูลที่ถูกบันทึกจากการเข้าใช้บริการ เช่น ชื่อผู้ใช้งานในการเข้าสู่ระบบ (Login ID) รหัสผ่าน (Password) คำถามและคำตอบเพื่อความปลอดภัย ภาพประจำตัวผู้ใช้งาน (Profile Picture) บันทึกข้อมูลการใช้งาน (Log File)

ทั้งนี้ เพื่อความจำเป็นในการให้บริการเพิ่มเติมนอกเหนือจากบริการพื้นฐานของบริษัท หรือกรณีเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลที่ความละเอียดอ่อน (Sensitive Personal Data) นอกเหนือจากที่ระบุข้างต้น บริษัทจะดำเนินการภายใต้ฐานต่าง ๆ ตามกฎหมายกำหนดเท่านั้น โดยบริษัทจะแจ้งวัตถุประสงค์ และประเภทของข้อมูลส่วนบุคคลที่ต้องการเก็บรวบรวม ใช้ หรือเปิดเผย ก่อนหรือขณะที่จะมีการดำเนินการดังกล่าว

##### **ฐานในการเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลของท่าน และวัตถุประสงค์ในการดำเนินการ**
บริษัทจะดำเนินการเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลของท่าน ภายใต้ฐานตามกฎหมายและดำเนินการตามวัตถุประสงค์ดังต่อไปนี้
* ฐานความจำเป็นต่อการปฏิบัติตามสัญญาซึ่งท่านเป็นคู่สัญญา หรือเพื่อใช้ในการดำเนินการตามคำขอของท่านก่อนเข้าทำสัญญา รวมถึงแต่ไม่จำกัดเพียง
 * การพิจารณาคำขอลงทะเบียนเข้าใช้บริการ 
 * การอื่นใดที่จำเป็นในการให้บริการที่ดีที่สุดจากบริษัท 
 * การให้บริการช่วยเหลือ ติดต่อสอบถามข้อมูล ตอบรับคำร้องขอ รับข้อมูลข่าวสาร หรือเพื่อการติดต่อสอบถามเกี่ยวกับบริการ
 * การพัฒนา ปรับปรุงคุณภาพการให้บริการ เพิ่มประสิทธิภาพในการให้บริการ และการอำนวยความสะดวกให้แก่ท่านในการเข้ารับบริการ
 * การประมวลผลข้อมูลเพื่อให้บริการ 
 * การดำเนินการอื่นใดที่เกี่ยวข้องกับการให้บริการและอาจเป็นประโยชน์ต่อท่าน
* ฐานการปฏิบัติหน้าที่ตามกฎหมาย รวมถึงแต่ไม่จำกัดเพียง
 * การปฏิบัติตามกฎหมายที่เกี่ยวข้องกับบริษัท ซึ่งบริษัทมีหน้าที่ต้องปฏิบัติตาม เพื่อให้เป็นไปตามกฎหมาย ระเบียบ กฎ หลักปฏิบัติ หรือแนวทางปฏิบัติใด ๆ ที่ออกโดยหน่วยงานตามกฎหมายหรือที่มีอำนาจกำกับดูแล โดยบริษัทอาจนำส่งข้อมูลส่วนบุคคลของท่านให้แก่ผู้ตรวจสอบภายใน/ภายนอก หน่วยงานราชการ หรือบุคคลนิติบุคคลอื่น ๆ ที่เกี่ยวข้อง
* ฐานความยินยอม รวมถึงแต่ไม่จำกัดเพียง
 * วัตถุประสงค์ทางการตลาด เช่น การเสนอสิทธิประโยชน์ และ/หรือเสนอขายสินค้าหรือบริการใด ๆ ที่อาจตรงกับความสนใจของท่าน, รายการส่งเสริมการขาย, การประชาสัมพันธ์, การสำรวจความคิดเห็นเกี่ยวกับบริการ ตลอดจนการสถิติ, วิเคราะห์, ศึกษาวิจัย, ประเมินผลข้อมูล หรือเพื่อจัดการความต้องการทางธุรกิจของบริษัท, คู่ค้าของบริษัทหรือบริษัทในเครือ ผ่านช่องทางการติดต่อที่ท่านได้แจ้งไว้ เช่น อีเมล เป็นต้น
 * วัตถุประสงค์อื่น ๆ อันชอบด้วยกฎหมายซึ่งบริษัทจะดำเนินการขอความยินยอมจากท่านเป็นคราว ๆ ไป เช่น เพื่ออำนวยความสะดวกให้แก่ท่านในการขอใช้บริการของผู้ให้บริการอื่นใดผ่านทางเว็บไซต์ แอปพลิเคชัน หรือระบบของบริษัท 
* ฐานประโยชน์โดยชอบด้วยกฎหมายของบริษัทหรือของบุคคลอื่น เว้นแต่ประโยชน์ดังกล่าวมีความสำคัญน้อยกว่าสิทธิขั้นพื้นฐานในข้อมูลส่วนบุคคลของท่าน รวมถึงแต่ไม่จำกัดเพียง
 * การป้องกันอาชญากรรมและการฉ้อโกง  
 * การรักษาความปลอดภัยของระบบและเครือข่ายเพื่อให้เป็นไปตามมาตรฐานสากล
* ฐานประโยชน์สาธารณะที่สำคัญ โดยบริษัทได้จัดให้มีมาตรการที่เหมาะสมเพื่อคุ้มครองสิทธิขั้นพื้นฐานและประโยชน์ของท่าน รวมถึงแต่ไม่จำกัดเพียง
 * การพิสูจน์/ยืนยันตัวตนเพื่อป้องกันอาชญากรรมและการฉ้อโกง
 * การต้องสงสัยเกี่ยวกับการสนับสนุนทางการเงินสำหรับการก่อการร้ายหรือการฟอกเงิน

นอกเหนือจากฐานตามกฎหมายและวัตถุประสงค์ข้างต้น บริษัทอาจดำเนินการเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลของท่านภายใต้ฐานอื่น ๆ ตามกฎหมาย เช่น เพื่อป้องกันหรือระงับอันตรายต่อชีวิต  ร่างกายหรือสุขภาพของท่าน เป็นต้น โดยหากมีการดำเนินการเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลภายใต้วัตถุประสงค์อื่น ๆ ตามฐานดังกล่าว บริษัทจะแจ้งให้ท่านทราบในภายหลัง

##### **การเปิดเผยข้อมูลส่วนบุคคลของท่านให้แก่บุคคลภายนอก และการเก็บรวบรวมข้อมูลส่วนบุคคลจากแหล่งอื่น**
เพื่อการดำเนินการตามวัตถุประสงค์และภายใต้ฐานตามกฎหมายของบริษัทข้างต้น บริษัทอาจเก็บรวบรวมจาก และ/หรือ ใช้, ส่ง, โอน, ประมวลผล และ/หรือเปิดเผยข้อมูลส่วนบุคคลให้แก่บุคคลดังต่อไปนี้
* นิติบุคคลที่มีอำนาจควบคุมบริษัท หรืออยู่ภายใต้การควบคุมของบริษัท รวมถึงบริษัทที่อยู่ภายใต้การควบคุมเดียวกันกับบริษัท ตลอดจนนิติบุคคล หรือบุคคลอื่นใดที่บริษัทเป็นคู่สัญญาหรือมีนิติสัมพันธ์กับบริษัท รวมถึงผู้ให้บริการอื่น ๆ ที่มีอำนาจดำเนินการใด ๆ กับข้อมูลส่วนบุคคลของท่าน ทั้งภายในและภายนอกประเทศ เช่น ผู้ให้บริการภายนอก ผู้ให้บริการ Cloud หรือคู่ค้าอื่นใดของบริษัท ทั้งนี้ บริษัทจะดำเนินการให้แน่ใจว่าผู้ให้บริการเหล่านั้นจะดำเนินการกับข้อมูลส่วนบุคคลของท่านตามนโยบายคุ้มครองข้อมูลส่วนบุคคลและกฎหมายที่เกี่ยวข้อง 
* ผู้สอบบัญชี ผู้ตรวจสอบภายนอกของบริษัท หน่วยงานราชการ ผู้รับโอนสิทธิเรียกร้อง และบุคคลหรือนิติบุคคลอื่นใด ที่บริษัทจำเป็นต้องส่งข้อมูลส่วนบุคคลให้เพื่อความจำเป็นในการปฏิบัติตามกฎหมาย
* ผู้รับโอนธุรกิจ/กิจการ ในกรณีที่บริษัทมีการควบรวม โอน ขาย ทรัพย์สิน และ/หรือกิจการทั้งหมด หรือแต่บางส่วน

##### **ระยะเวลาการเก็บรักษาข้อมูลส่วนบุคคลของท่าน**
บริษัทมีความจำเป็นที่จะต้องเก็บรวบรวมข้อมูลส่วนบุคคลของท่านไว้ เป็นระยะเวลาเท่าที่จำเป็นในระหว่างที่ท่านยังใช้บริการหรือมีความสัมพันธ์อยู่กับบริษัท หรือตลอดระยะเวลาเท่าที่จำเป็นเพื่อให้บรรลุวัตถุประสงค์ที่เกี่ยวข้องกับการให้บริการของบริษัท โดยอาจเก็บรวบรวมไว้ต่อไปภายหลังจากนั้นหากมีกฎหมายกำหนดไว้ หรือเพื่อวัตถุประสงค์ในการพิสูจน์ตรวจสอบกรณีอาจเกิดข้อพิพาทภายในอายุความตามที่กฎหมายกำหนดเป็นระยะเวลาไม่เกิน 10 ปี
ทั้งนี้ บริษัทจะลบหรือทำลายข้อมูลส่วนบุคคล หรือทำให้เป็นข้อมูลที่ไม่สามารถระบุถึงตัวตนของท่านได้เมื่อหมดความจำเป็นหรือสิ้นสุดระยะเวลาดังกล่าวแล้ว

##### **การรักษาความปลอดภัย**
บริษัทรับทราบและตระหนักถึงความสำคัญของข้อมูลส่วนบุคคลของท่าน บริษัทจึงได้ปรับปรุงและพัฒนาระบบรักษาความปลอดภัยข้อมูลส่วนบุคคลของท่านให้สอดคล้องกับกฎหมาย และทันสมัยและปลอดภัยตามหลักมาตรฐานสากลตลอดเวลา บริษัทจะดำเนินการอย่างเต็มความสามารถเพื่อปฏิบัติตามนโยบายการคุ้มครองข้อมูลส่วนบุคคลนี้ และเน้นย้ำให้เจ้าหน้าที่ รวมถึงผู้ประมวลผลข้อมูลส่วนบุคคลของบริษัทที่มีสิทธิเข้าถึงข้อมูลส่วนบุคคล หรือมีหน้าที่ตามกฎหมาย รักษาและเคารพซึ่งความปลอดภัยของข้อมูลส่วนบุคคลของท่าน

ในกรณีที่ทางบริษัทมีความจำเป็นหรือต้องโอนข้อมูลส่วนบุคคลใด ๆ ของท่านไปยังต่างประเทศ บริษัทจะใช้มาตรฐานตามที่กฎหมายในเรื่องการคุ้มครองข้อมูลส่วนบุคคลกำหนด และบริษัทจะไม่โอนข้อมูลส่วนบุคคลของท่านไปยังประเทศปลายทางที่ไม่มีมาตรฐานการคุ้มครองข้อมูลส่วนบุคคลที่เพียงพอตามหลักเกณฑ์ที่กฎหมายกำหนด เว้นแต่ท่านยินยอมให้บริษัทส่งหรือโอนข้อมูลส่วนบุคคลของท่านไปยังประเทศปลายทางดังกล่าวได้ อย่างไรก็ตาม ในกรณีที่ข้อมูลส่วนบุคคลของผู้ใช้บริการถูกจารกรรมทางคอมพิวเตอร์ ไม่ว่าด้วยวิธีการเจาะระบบ (hacking) ขโมย สำเนา หรือทำลายฐานข้อมูล ทำลายรหัสลับส่วนตัว (password mining) หรือวิธีการอื่นใด ซึ่งมิใช่ความผิดของบริษัท บริษัทมีสิทธิที่จะปฏิเสธความรับผิดใดๆ อันเป็นผลมาจากการกระทำดังกล่าว

##### **สิทธิของท่าน**
ท่านมีสิทธิดังต่อไปนี้
* ขอเข้าถึงข้อมูลส่วนบุคคลของตนเองซึ่งอยู่กับบริษัทและขอรับสำเนาข้อมูลส่วนบุคคลที่เกี่ยวข้องกับตน หรือขอให้เปิดเผยถึงการได้มาซึ่งข้อมูลส่วนบุคคลที่ตนไม่ได้ให้ความยินยอม
* ขอรับข้อมูลส่วนบุคคลของตนเอง ในรูปแบบที่สามารถอ่านหรือใช้งานได้โดยทั่วไปโดยเครื่องมือ หรืออุปกรณ์          ที่ทำงานโดยอัตโนมัติ หรือใช้หรือเปิดเผยข้อมูลส่วนบุคคลดังกล่าวโดยวิธีอัตโนมัติ (ในกรณีที่บริษัทจัดทำ), หรือ ขอให้บริษัทส่งหรือโอนข้อมูลส่วนบุคคลดังกล่าวไปยังผู้ควบคุมข้อมูลส่วนบุคคลรายอื่นตามที่กฎหมายกำหนด และรวมถึง ขอรับข้อมูลส่วนบุคคลของตนที่บริษัทส่งหรือโอนแก่ผู้ควบคุมข้อมูลส่วนบุคคลรายอื่น (เว้นแต่ทางเทคนิคไม่สามารถที่จะทำได้)
* คัดค้านการเก็บรวบรวม ใช้ หรือ เปิดเผยข้อมูลส่วนบุคคลของตนตามที่กฎหมายกำหนด
* ขอให้บริษัทลบ หรือทำลาย ระงับการใช้ชั่วคราว หรือแปลงข้อมูลส่วนบุคคลให้อยู่ในรูปแบบข้อมูลที่ไม่สามารถรู้ตัวบุคคลที่เป็นเจ้าของข้อมูลได้ 
* ขอให้บริษัทระงับการใช้ข้อมูลส่วนบุคคลของตน
* ขอให้บริษัทดำเนินการแก้ไขหรือเพิ่มเติมข้อมูลส่วนบุคคลให้ถูกต้อง เป็นปัจจุบัน สมบูรณ์ และไม่ก่อให้เกิดความเข้าใจผิด
ทั้งนี้ บริษัทมีสิทธิแก้ไขหรือเพิ่มเติมข้อมูลส่วนบุคคลที่ไม่ถูกต้องตามความจริงใด ๆ ที่ท่านใช้หรือแสดงแก่บริษัทเพื่อรับบริการ ภายหลังจากที่บริษัทได้รับข้อมูลส่วนบุคคลที่ถูกต้องพร้อมหลักฐานสนับสนุน โดยถือเป็นดุลยพินิจของบริษัทในการพิจารณา
* หากท่านประสงค์ที่จะยกเลิกการใช้บริการ ท่านสามารถเพิกถอนความยินยอมที่ได้ให้แก่บริษัทได้โดยวิธีการตามที่บริษัทกำหนด การเพิกถอนความยินยอมดังกล่าวย่อมไม่ส่งผลกระทบต่อการเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลที่ท่านได้ให้ความยินยอมไปแล้ว
* ร้องเรียนในกรณีที่บริษัท ฝ่าฝืนไม่ปฏิบัติตามนโยบายการคุ้มครองข้อมูลลส่วนบุคคลต่อหน่วยงานที่มีอำนาจ

อย่างไรก็ตาม ท่านรับทราบว่าสิทธิดังกล่าวเป็นสิทธิเบื้องต้น ท่านจะใช้สิทธิดังกล่าวได้ต้องเป็นไปตามเงื่อนไขตามกฎหมายที่เกี่ยวข้อง และบริษัทในฐานะผู้ควบคุมข้อมูลส่วนบุคคลดังกล่าว มีสิทธิตามกฎหมายที่จะปฏิเสธการใช้สิทธิดังกล่าวของท่าน

หากท่านประสงค์จะใช้สิทธิของท่านภายใต้กฎหมายคุ้มครองข้อมูลส่วนบุคคล บริษัทจะตอบกลับอย่างทันท่วงที และจะใช้ความพยายามในการดำเนินการตามคำร้องขอของท่านโดยไม่มีค่าบริการ ภายในกำหนดเวลา 1 เดือน หลังจากได้รับเอกสารที่เกี่ยวข้องครบถ้วน ทั้งนี้ โปรดตระหนักว่า บริษัทอาจเรียกเก็บค่าบริการสำหรับคำร้องขอที่ซับซ้อน ไม่สมเหตุสมผล ฟุ่มเฟือยเกินความจำเป็น หรือซ้ำซ้อน

##### **ข้อมูลส่วนบุคคลของผู้เยาว์**
บริษัทจะเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลของผู้เยาว์ให้เป็นไปตามมาตรฐานที่กฎหมายกำหนดเท่านั้น ทั้งนี้ หากบริษัททราบว่าได้มีการนำข้อมูลส่วนบุคคลของผู้เยาว์เข้าระบบของบริษัท บริษัทจะดำเนินการตามขั้นตอนที่เหมาะสมเพื่อจัดการกับข้อมูลดังกล่าวโดยเร็ว

##### **ภาษา**
การแปลนโยบายการคุ้มครองข้อมูลส่วนบุคคลฉบับนี้ ไม่ว่าจะแปลเป็นภาษาใดก็ตาม มีไว้เพื่ออำนวยความสะดวกของท่านเท่านั้น ไม่ได้มีเจตนาใด ๆ ที่จะปรับเปลี่ยนนโยบายการคุ้มครองข้อมูลส่วนบุคคล ในกรณีที่มีข้อความขัดแย้งกันระหว่างฉบับภาษาไทยและภาษาอื่น ๆ ที่ไม่ใช่ภาษาไทย ให้ยึดข้อความตามภาษาไทย

##### **การติดต่อ**
หากท่านมีคำถาม ข้อร้องเรียน การขอเข้าถึง หรือข้อสงสัยใด ๆ เกี่ยวข้องกับนโยบายการคุ้มครองข้อมูลส่วนบุคลนี้ และ/หรือต้องการตรวจสอบว่าข้อมูลส่วนบุคคลใดของท่านอยู่ในความครอบครองของบริษัท ท่านสามารถติดต่อสอบถามได้ผ่านช่องทางของบริษัท ดังนี้

###### **ศูนย์บริการลูกค้า (Customer Care)**
ที่อยู่ 	: 1168/94 อาคารลุมพินีทาวเวอร์ ชั้นที่ 31 ถนนพระราม 4 แขวงทุ่งมหาเมฆ เขตสาทร กรุงเทพมหานคร 10120

โทรศัพท์	: 0-2034-4333

โทรสาร	: 0-2679-7474

อีเมล	: customercare@pantavanij.com 

###### **เจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล (DPO)**
ที่อยู่ 	: .................

โทรศัพท์	: .................

อีเมล	: ................

##### **การปรับปรุงนโยบาย**
อนึ่ง การใช้บริการใด ๆ ของบริษัท ถือเป็นการยอมรับนโยบายการคุ้มครองข้อมูลส่วนบุคคลฉบับนี้ บริษัทอาจแก้ไขหรือเพิ่มเติมนโยบายการคุ้มครองข้อมูลส่วนบุคคลฉบับนี้ได้ไม่ว่าในเวลาใด ๆ และแจ้งให้ท่านทราบ การที่ท่านใช้บริการเว็บไซต์ แอปพลิเคชัน หรือระบบของบริษัทหรือบริการใด ๆ ภายหลังจากที่มีการประกาศแก้ไขหรือเพิ่มเติมดังกล่าวย่อมถือเป็นการยอมรับการแก้ไขหรือเพิ่มเติมแต่ละครั้ง`;
